### ISSUE TITLE
Feature Request: Get rid off of bluebird dependency

### ISSUE THREAD

**Issue by mwittig** [jut-io/bluebird-retry#5]
It would be great if you can get rid of the dependency on bluebird to avoid the bluebird package is getting loaded multiple times. This is very easy to do - see promise-retryer, for example

**Comment by demmer** [comment]
I hadn't noticed promise-retryer previously.

I'm not sure if there are substantive feature differences between the two, but from my standpoint I'm happy with the current model that bluebird-retry uses since it's more convenient from the caller. If you prefer the other approach then it seems like promise-retryer would be a better fit for you.

**Comment by mwittig** [comment]
OK, fair enough.My concern is that possibly different versions of bluebird will be used in a single application which can have strange side effects.

promise-retryer does not support "retry forever" and has no "backoff" feature. Both should be easy to implement, however. For the time being I'll continue using bluebird-retry.

**Comment by demmer** [comment]
Fair point... It seems like a good solution to this would be to change from a dependency on ^2.3.10 to >=2.3.10.

That way if there's a compatible bluebird installation in the containing project then it will use it rather than installing another copy.
